#基础镜像
FROM openjdk:8-jdk-alpine
LABEL maintainer="yaokun <yaokun@bwcxtech.com>"
#构建参数
ARG JAR_FILE="wcpt-server.jar"
#环境变量
ENV TZ "Asia/Shanghai"
ENV JAR_FILE=${JAR_FILE}
#复制项目
COPY ./target/${JAR_FILE} /home/
#工作空间
WORKDIR /home
#监听端口
EXPOSE 8080
#启动
ENTRYPOINT exec java ${JAVA_OPTS} -jar ${JAR_FILE}