#!groovy

@Library('jenkinslibrary@master') _

//func from shareibrary
def build = new org.devops.build()
def tools = new org.devops.tools()


//pipeline
pipeline{
    agent any

    // 指定运行的选项（可选）
    options {
        // 删除隐式checkout scm语句
        skipDefaultCheckout()
        //保持构建的最大个数
        buildDiscarder(logRotator(numToKeepStr: '5'))
        // 设置Pipeline运行的超时时间
        //timeout(time: 1, unit: 'HOURS')
        // 日志会有时间
        //timestamps()
        // 禁止并行
        //disableConcurrentBuilds()
    }
    
    // 参数化变量
    parameters {
    // 构建类型
    string(name:'buildType', defaultValue: 'mvn', description: '构建类型')
    // 构建命令
    string(name:'buildShell', defaultValue: 'clean install -DskipTests', description: '构建命令')
    // 镜像仓库
    choice choices: ['local', 'aliyun', 'huaweicloud'], description: '镜像仓库', name: 'registry'
    }

    stages{

       stage("checkout") {
            steps {
                script{
                    tools.PrintMes("检出代码","green")
                    checkout scm
                }
            }
        }

        stage("Build"){
            steps{
                script{
                    tools.PrintMes("执行打包","green")
                    build.Build(buildType,buildShell)
                }
            }
        }
        // 构建镜像
        stage("BuildImages"){
            steps{
                script{
                    tools.PrintMes("构建上传镜像","green")
                sh """
                curl http://192.168.1.83/other/devops/raw/master/resources/org/foo/push_1of2.sh | sh -s ${registry}
                """
                }
            }
        }
    }

}
