#!groovy

@Library('jenkinslibrary@master') _

// func from shareibrary
def tools = new org.devops.tools()
def checkout = new org.devops.checkout()
def maven = new org.devops.maven()
def docker = new org.devops.docker()

// 读取资源文件
def podYaml = libraryResource 'org/devops/pipeline/podyaml/MavenPod.yaml'

// pipeline
pipeline{
    agent{
        kubernetes{
            inheritFrom 'jenkins-slave'
            defaultContainer 'maven'
            yaml podYaml
            showRawYaml false
        }
    }

    environment {
        repo = "yuanfu-tms"
    }

    // 指定运行的选项（可选）
    options {
        // 删除隐式checkout scm语句
        skipDefaultCheckout()
        // 保持构建的最大个数
        buildDiscarder logRotator(artifactDaysToKeepStr: '1', artifactNumToKeepStr: '5', numToKeepStr: '5')
        // 设置Pipeline运行的超时时间
        // timeout(time: 1, unit: 'HOURS')
        // 日志会有时间
        // timestamps()
        // 禁止并行
        disableConcurrentBuilds()
    }
    
    // 参数化变量
    parameters {
    // 构建工具参数
    string(name: 'BUILD_ARGS', defaultValue: '', description: '可选的构建工具参数')
    // 镜像仓库
    choice choices: ['local', 'aliyun', 'huaweicloud'], description: '镜像仓库', name: 'REGISTRY'
    }

    stages{

       stage("Checkout") {
            steps {
                container('maven'){
                    script{
                        tools.PrintMes("检出代码","green")
                        checkout.checkoutCustom()
                    }
                }
            }
        }

        stage("Build"){
            steps{
                container('maven'){
                    script{
                        tools.PrintMes("执行打包","green")
                        maven.build(params.BUILD_ARGS ?: '')
                    }
                }
            }
        }

        // 构建镜像
        stage("Building Container Images"){
            steps{
                container('docker'){
                    script{
                        tools.PrintMes("构建镜像","green")
                        docker.docker()
                        docker.build(project: "demo").push()
                    }
                }
            }
        }
        
    }

    post {
        success {
            archiveArtifacts artifacts: '**/target/*.jar, **/target/*.war', fingerprint: true
        }
        failure {
            echo '构建失败'
        }
    }

}
