#!groovy

@Library('jenkinslibrary@master') _

//func from shareibrary
def build = new org.devops.build()
def deploy = new org.devops.deploy()
def tools = new org.devops.tools()
def gitlab = new org.devops.gitlab()
def toemail = new org.devops.toemail()
def sonar = new org.devops.sonarqube()
def sonarapi = new org.devops.sonarapi()
def nexus = new org.devops.nexus()
def artifactory = new org.devops.artifactory() 
def k8s = new org.devops.kubernetes()

def runOpts
//env
String srcUrl = "${env.srcUrl}"
String branchName = "${env.branchName}"
String buildType = "${env.buildType}"
String buildShell = "${env.buildShell}"
String registry = "${env.registry}"


//pipeline
pipeline{
    agent { node { label "build"}}

    // 指定运行的选项（可选）
    options {
        // 删除隐式checkout scm语句
        skipDefaultCheckout()
        //保持构建的最大个数
        buildDiscarder(logRotator(numToKeepStr: '5'))
        // 设置Pipeline运行的超时时间
        //timeout(time: 1, unit: 'HOURS')
        // 日志会有时间
        //timestamps()
        // 禁止并行
        //disableConcurrentBuilds()
    }
    
    // 参数化变量
    parameters {
    // git代码路径【参数值对外隐藏】
    string(name:'srcUrl', defaultValue: 'http://192.168.1.83/tms/tms.git', description: 'git代码路径')
    // 构建类型
    string(name:'buildType', defaultValue: 'mvn', description: '构建类型')
    // 构建命令
    string(name:'buildShell', defaultValue: 'clean install -DskipTests', description: '构建命令')
    // git分支
    gitParameter branchFilter: 'origin/(.*)', defaultValue: 'dev', name: 'branchName', type: 'PT_BRANCH', description: '构建分支'
    // 镜像仓库
    choice choices: ['local', 'aliyun', 'huaweicloud'], description: '镜像仓库', name: 'registry'
    }

    stages{

       stage("GetCode"){
            steps{
                script{
                    println("${branchName}")
                    tools.PrintMes("获取代码","green")
                    checkout([$class: 'GitSCM', branches: [[name: "${branchName}"]], 
                                      doGenerateSubmoduleConfigurations: false, 
                                      extensions: [], 
                                      submoduleCfg: [], 
                                      userRemoteConfigs: [[credentialsId: 'gitlab-admin-user', url: "${srcUrl}"]]])
                }
            }
        }
        stage("Build"){
            steps{
                script{
                    tools.PrintMes("执行打包","green")
                    build.Build(buildType,buildShell)
                }
            }
       }
           // 构建镜像
           stage("BuildImages"){
                steps{
                    script{
                        tools.PrintMes("构建上传镜像","green")
                sh """
                curl http://192.168.1.83/tms/script/raw/master/push_1of3.sh | sh -s ${registry}
                """
                }
            }
        }
           // gittag
           stage("gittag"){
                when {
                    branch 'dev'
                }
                steps{
                    script{
                        tools.PrintMes("gittag","green")
                sh """
                echo ${BUILD_TIMESTAMP}
                git tag -a -m 'Release version ${BUILD_TIMESTAMP}' ${BUILD_TIMESTAMP}
                git push origin --tags
                echo 'git标签添加成功'
                """
                }
            }
        }
    }
    
}
