# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - localhost:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    file_sd_configs:
    - refresh_interval: 1m
      files: 
      - targets/nodes/*.yml

  - job_name: "blackbox-http"
    metrics_path: /probe # 不是 metrics，是 probe
    params:
      module: [http_2xx] # 使用 http_2xx 模块
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - targets/blackbox/http_2xx.yml
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115  # blackbox服务地址

  - job_name: "blackbox-http-post"
    metrics_path: /probe # 不是 metrics，是 probe
    params:
      module: [http_post_2xx] # 使用 http_2xx 模块
    file_sd_configs:
    - refresh_interval: 1m
      files:
      - targets/blackbox/http_post_2xx.yml
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115  # blackbox服务地址
