kind: ConfigMap
apiVersion: v1
metadata:
  creationTimestamp: "2021-03-09T02:09:42Z"
  name: test-config2
  namespace: default
data:
  tms.properties: |
    db.host.url=jdbc:oracle:thin:@192.168.1.181:1521:orcl
    db.host.user=tms_user_1
    db.host.pwd=tms_uat_pwd

    contractUrl.prefix = http://api:8080/yfapi/

    contract.bank.auth.method=contract.bank.auth
    contract.person.auth.method=contract.person.auth
    contract.app_key=6019D5A6FAB24E13AD2AE917D9A54EE7
    person.auth=/api/contract/person/auth
    bank.auth=/api/contract/bank/auth
