global:
  resolve_timeout: 5m
route:
  receiver: webhook
  group_by: [alertname]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - receiver: webhook
    group_wait: 10s
receivers:
- name: webhook
  webhook_configs:
  - url: http://localhost:8060/dingtalk/webhook/send  
    send_resolved: true
