global:
  resolve_timeout: 5m
route:
  group_by: [instance]
  group_wait: 10m
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'web.hook.prometheusalert'
receivers:
- name: 'web.hook.prometheusalert'
  webhook_configs:
  - url: http://localhost:8060/prometheusalert?type=dd&tpl=prometheus2-dd
    send_resolved: true
