groups:
  - name: 网络-监控告警
    rules:

      - alert: BlackboxProbeDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
          threshold: "probe_success == 0"
          for_time: "1分钟"
        annotations:
          description: "{{ $labels.instance }} 连续 1 分钟无法访问"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 5m
        labels:
          severity: critical
          threshold: "HTTP 状态码 ≤199 或 ≥400"
          for_time: "5分钟"
        annotations:
          description: "{{ $labels.instance }} 返回异常 HTTP 状态码 ({{ $value }})"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: 3 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 20
        for: 0m
        labels:
          severity: warning
          threshold: "20"
        annotations:
          summary: "{{ $labels.instance }} SSL证书即将过期"
          description: |
            {{ $labels.instance }} SSL证书过期时间小于20天
            剩余天数: {{ printf "%.1f" $value }}
      
      - alert: BlackboxSslCertificateWillExpireSoon
        expr: 0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 3
        for: 0m
        labels:
          severity: critical
          threshold: "3"
        annotations:
          summary: "{{ $labels.instance }} SSL证书即将过期"
          description: |
            {{ $labels.instance }} SSL证书过期时间小于3天
            剩余天数: {{ printf "%.1f" $value }}
