groups:
  - name: blackbox_network_stats
    rules:

      - alert: BlackboxProbeDown
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
          threshold: "probe_success == 0"
          for_time: "1分钟"
        annotations:
          description: "{{ $labels.instance }} 连续 1 分钟无法访问 (probe_success=0)"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 5m
        labels:
          severity: critical
          threshold: "HTTP 状态码 ≤199 或 ≥400"
          for_time: "5分钟"
        annotations:
          description: "{{ $labels.instance }} 返回异常 HTTP 状态码 ({{ $value }})"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 3
        for: 5m
        labels:
          severity: warning
          threshold: "SSL证书有效期 < 3天"
          for_time: "5分钟"
        annotations:
          description: "{{ $labels.instance }} 的 SSL 证书将在 {{ $value | humanizeTimestamp }} 过期（剩余时间不足3天）"
