groups:
- name: Windows主机状态-监控告警
  rules:
  - alert: WindowsServerCollectorError
    expr: windows_exporter_collector_success == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} Windows Server 采集器错误"
      description: 采集器 {{ $labels.collector }} 没有成功\n  VALUE = {{ $value }}

  - alert: WindowsServerServiceStatus
    expr: windows_service_status{status="ok"} != 1
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} Windows Server 服务状态"
      description: Windows Service state is not OK\n  VALUE = {{ $value }}

  - alert: WindowsServerCpuUsage
    expr: 100 - (avg by (instance) (rate(windows_cpu_time_total{mode="idle"}[2m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "{{ $labels.instance }} Windows Server CPU 使用率"
      description: CPU 使用率超过 80%\n  VALUE = {{ $value }}

  - alert: WindowsServerMemoryUsage
    expr: 100 - ((windows_os_physical_memory_free_bytes / windows_cs_physical_memory_bytes) * 100) > 90
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "{{ $labels.instance }} Windows Server 内存使用率"
      description: 内存使用率超过 90%\n  VALUE = {{ $value }}

  - alert: WindowsServerDiskSpaceUsage
    expr: 100.0 - 100 * ((windows_logical_disk_free_bytes / 1024 / 1024 ) / (windows_logical_disk_size_bytes / 1024 / 1024)) > 80
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} Windows Server 磁盘使用率"
      description: 磁盘使用率超过 80%\n  VALUE = {{ $value }}

  - alert: 网络流入带宽过载
    expr: (irate(windows_net_bytes_received_total{nic!~'isatap.*|VPN.*'}[5m])*8 /1000) > 5120
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} 流入（下载）网络带宽过高！"
      description: "{{ $labels.instance }} 流入（下载）网络带宽持续2分钟高于5M. RX带宽使用率{{$value}}"

  - alert: 网络流出带宽过载
    expr: (irate(windows_net_bytes_sent_total{nic!~'isatap.*|VPN.*'}[5m])*8 /1000) > 5120
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "{{ $labels.instance }} 流出（上传）网络带宽过高！"
      description: "{{ $labels.instance }} 流出（上传）网络带宽持续2分钟高于5M. RX带宽使用率{{$value}}"
