#!groovy

@Library('jenkinslibrary@master') _

// func from shareibrary
def tools = new org.devops.tools()
def checkout = new org.devops.checkout()
def maven = new org.devops.maven()
def docker = new org.devops.docker()
def kubectl = new org.devops.kubectl()

// 读取资源文件
def podYaml = libraryResource 'org/devops/pipeline/podyaml/MavenPod.yaml'

// pipeline
pipeline{
    agent{
        kubernetes{
            defaultContainer 'maven'
            inheritFrom 'jenkins-slave'
            yaml podYaml
            showRawYaml false
        }
    }

    environment {
        repo = "public"
        k8s_namespace = "default"
    }

    // 指定运行的选项（可选）
    options {
        // 删除隐式checkout scm语句
        skipDefaultCheckout()
        // 保持构建的最大个数
        buildDiscarder logRotator(artifactDaysToKeepStr: '1', artifactNumToKeepStr: '5', numToKeepStr: '5')
        // 设置Pipeline运行的超时时间
        // timeout(time: 1, unit: 'HOURS')
        // 日志会有时间
        // timestamps()
        // 禁止并行并终止旧构建
        disableConcurrentBuilds abortPrevious: true
    }
    
    // 参数化变量
    parameters {
    // 构建工具参数
    string(name: 'BUILD_ARGS', defaultValue: '', description: '可选的构建工具参数')
    // 构建环境
    choice choices: ['dev', 'prod'], description: '构建环境', name: 'BUILD_ENV'
    // 镜像仓库
    choice choices: ['local', 'aliyun', 'huaweicloud'], description: '镜像仓库', name: 'REGISTRY'
    }

    stages{

       stage("checkout") {
            steps {
                container('maven'){
                    script{
                        tools.PrintMes("检出代码","green")
                        checkout.checkoutCustom()
                    }
                }
            }
        }

        stage("Build"){
            steps{
                container('maven'){
                    script{
                        tools.PrintMes("执行打包","green")
                        maven.deploy(params.BUILD_ARGS ?: '')
                    }
                }
            }
        }

        // 构建镜像
        stage("BuildImages"){
            steps{
                container('docker'){
                    script{
                        tools.PrintMes("构建镜像","green")
                        docker.docker()
                        docker.build(path: "my-demo", project: "demo").push()
                    }
                }
            }
        }

        // 发布
        stage("Deploy"){
            steps{
                container('kubectl'){
                    script{
                        tools.PrintMes("发布","green")
                        kubectl.init()
                        kubectl.deploy(project: "demo")
                    }
                }
            }
        }

    }

}

    post {
        success {
            archiveArtifacts artifacts: '**/build/libs/*.jar, **/build/libs/*.war', allowEmptyArchive: true
        }
        failure {
            echo '构建失败'
        }
    }

}
