variables:
    MAVEN_OPTS: "-Dmaven.repo.local=/usr/share/maven/repository"
    MAVEN_CLI_OPTS: "--batch-mode --settings /usr/share/maven/configmap/settings.xml"

# cache:
#   paths:
#     - .m2/repository

.job_template: &job_configuration  # Hidden yaml configuration that defines an anchor named 'job_configuration'
  image: maven:3.6.2

stages:
- build
- deploy

compile:
  <<: *job_configuration           # Merge the contents of the 'job_configuration' alias
  # image: maven:3.6.2
  stage: build
  script:
  - echo "=============== 开始打包任务  ==============="
  - mvn $MAVEN_CLI_OPTS install
  artifacts:
    name: "jars"
    expire_in: 60 mins
    paths:
      - target/*.jar
    when: on_success

deploy:
  <<: *job_configuration           # Merge the contents of the 'job_configuration' alias
  # image: maven:3.6.2
  stage: deploy
  script:
  - echo "=============== 开始推送制品  ==============="
  - mvn $MAVEN_CLI_OPTS deploy
