stages:
  - verify

other_merge_branch:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME != "main"'
      when: always
    - when: never  # 默认情况下不运行
  stage: verify
  script:
    - echo "This merge request targets a branch other than 'main'. Skipping verification."

verify_merge_branch:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - when: never  # 默认情况下不运行
  stage: verify
  script:
    - |
      if [[ "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" != "develop" && "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" != hotfix/* ]]; then
        echo "Only 'develop' or 'hotfix/*' branches can be merged into main."
        exit 1
      fi
